name: dialysis_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Charts
  table_calendar: ^3.2.0
  fl_chart: ^0.69.0

  # PDF and Printing
  pdf: ^3.11.0
  printing: ^5.12.0

  # Firebase (FlutterFire plugins)
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3

  # Auth and Utils
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  shared_preferences: ^2.5.3

  # Lints
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
