name: dialysis_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  fl_chart: ^1.1.1
  printing: ^5.10.0
  pdf: ^3.10.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3

  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  image_picker: ^1.0.7
  intl: ^0.20.2

  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


assets:
  - assets/logo/
