// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHj3oyhYqOCl-VifBQzKLpD2lX8nlMGk',
    appId: '1:305346711737:web:a5402516c534b62b40cb68',
    messagingSenderId: '305346711737',
    projectId: 'dialysis-app-a008c',
    authDomain: 'dialysis-app-a008c.firebaseapp.com',
    storageBucket: 'dialysis-app-a008c.firebasestorage.app',
    measurementId: 'G-HCYKSGGPG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApc0bgizXrHSo8KFa8eMu_WHN71R3JMbM',
    appId: '1:305346711737:android:1fdcae6e6fb4857440cb68',
    messagingSenderId: '305346711737',
    projectId: 'dialysis-app-a008c',
    storageBucket: 'dialysis-app-a008c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiYEuQzfB2Tx0ULIGDLIznzAwwC8zE3Y4',
    appId: '1:305346711737:ios:fbbbcd4ba3e1929d40cb68',
    messagingSenderId: '305346711737',
    projectId: 'dialysis-app-a008c',
    storageBucket: 'dialysis-app-a008c.firebasestorage.app',
    iosBundleId: 'com.example.dialysisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiYEuQzfB2Tx0ULIGDLIznzAwwC8zE3Y4',
    appId: '1:305346711737:ios:fbbbcd4ba3e1929d40cb68',
    messagingSenderId: '305346711737',
    projectId: 'dialysis-app-a008c',
    storageBucket: 'dialysis-app-a008c.firebasestorage.app',
    iosBundleId: 'com.example.dialysisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcHj3oyhYqOCl-VifBQzKLpD2lX8nlMGk',
    appId: '1:305346711737:web:3d380a7a9b154bf240cb68',
    messagingSenderId: '305346711737',
    projectId: 'dialysis-app-a008c',
    authDomain: 'dialysis-app-a008c.firebaseapp.com',
    storageBucket: 'dialysis-app-a008c.firebasestorage.app',
    measurementId: 'G-KP0GX7TDSF',
  );
}
